[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18.20.2"

[[redirects]]
  from = "/docs/tech-stack/"
  to = "/about/tech-stack/"

[[redirects]]
  status = 302
  from = "/discord/"
  to = "https://discord.gg/dmDmjFCKuH"